name: Next.js CI Dev

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Start Services
        run: docker compose up -d --build

      - name: Wait for App to be Ready
        run: |
          for i in {1..10}; do
            curl -s http://web:3000 && break
            echo "Waiting for app..."
            sleep 3
          done

      - name: Run Tests
        run: curl -f http://web:3000 || exit 1

      - name: Stop and Clean Up
        run: docker compose down

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Push Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/dev-ops-nextjs .
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/dev-ops-nextjs
