name: Dockerized Next.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      # secrets.SECRET_NAME
      ENV_VAR: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Start Services
        run: docker compose up -d --build

      - name: Wait for App to be Ready
        run: |
          for i in {1..10}; do
            curl -s http://web:3000 && break
            echo "Waiting for app..."
            sleep 3
          done

      - name: Run Tests
        run: curl -f http://web:3000 || exit 1

      - name: Stop and Clean Up
        run: docker compose down
